language: python
cache: pip
addons:
  apt:
    packages:
      - libsnappy-dev
      - oracle-java8-set-default
install:
  - pip install tox-travis codecov flake8
script:
  - tox
  - flake8 usage_report/ tests/ --max-line-length 100
after_success:
  - codecov
